services:
  nifi:
    image: apache/nifi:2.9.0
    container_name: nifi-light
    restart: unless-stopped
    ports:
      - "8443:8443"
    env_file:
      - .env
    environment:
      NIFI_WEB_HTTPS_PORT: "8443"
      NIFI_WEB_HTTPS_HOST: "0.0.0.0"
      NIFI_WEB_PROXY_HOST: "localhost:8443,127.0.0.1:8443"
      NIFI_CLUSTER_IS_NODE: "false"
      NIFI_JVM_HEAP_INIT: "256m"
      NIFI_JVM_HEAP_MAX: "512m"
      NIFI_SENSITIVE_PROPS_KEY: "${NIFI_SENSITIVE_PROPS_KEY}"
      SINGLE_USER_CREDENTIALS_USERNAME: "${NIFI_USERNAME}"
      SINGLE_USER_CREDENTIALS_PASSWORD: "${NIFI_PASSWORD}"
    volumes:
      - nifi-conf:/opt/nifi/nifi-current/conf
      - nifi-state:/opt/nifi/nifi-current/state
      - nifi-database:/opt/nifi/nifi-current/database_repository
      - nifi-flowfile:/opt/nifi/nifi-current/flowfile_repository
      - nifi-content:/opt/nifi/nifi-current/content_repository
      - nifi-provenance:/opt/nifi/nifi-current/provenance_repository
      - nifi-nar:/opt/nifi/nifi-current/nar_extensions
      - nifi-python:/opt/nifi/nifi-current/python_extensions
      - nifi-logs:/opt/nifi/nifi-current/logs

volumes:
  nifi-conf:
  nifi-state:
  nifi-database:
  nifi-flowfile:
  nifi-content:
  nifi-provenance:
  nifi-nar:
  nifi-python:
  nifi-logs:
