{
  "type": "record",
  "name": "prod__cmdb__assets",
  "namespace": "bronze",
  "fields": [
    {
      "name": "sl_no",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "hostname",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "ip_address",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "mac_address",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "device_type",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "manufacturer_model",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "operating_system",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "os_type",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "role_function",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "applications",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "database",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "location",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "zone",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "priority_business_impact",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "status",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "services_enabled",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "asset_owner_name",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "asset_owner_contact",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "asset_owner_email",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "notes",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "organization_name",
      "type": [
        "null",
        "string"
      ],
      "default": null
    }
  ]
}
