{
  "type": "record",
  "name": "rapid7",
  "namespace": "bronze",
  "fields": [
    {
      "name": "addresses",
      "type": [
        {
          "type": "array",
          "items": [
            {
              "type": "record",
              "name": "addresses",
              "namespace": "bronze.rapid7",
              "fields": [
                {
                  "name": "ip",
                  "type": [
                    "string",
                    "null"
                  ]
                },
                {
                  "name": "mac",
                  "type": [
                    "string",
                    "null"
                  ]
                }
              ]
            },
            "null"
          ]
        },
        "null"
      ]
    },
    {
      "name": "assessedForPolicies",
      "type": [
        "boolean",
        "null"
      ]
    },
    {
      "name": "assessedForVulnerabilities",
      "type": [
        "boolean",
        "null"
      ]
    },
    {
      "name": "files",
      "type": [
        {
          "type": "array",
          "items": [
            {
              "type": "record",
              "name": "files",
              "namespace": "bronze.rapid7",
              "fields": [
                {
                  "name": "attributes",
                  "type": [
                    {
                      "type": "array",
                      "items": [
                        {
                          "type": "record",
                          "name": "attributes",
                          "namespace": "bronze.rapid7.files",
                          "fields": [
                            {
                              "name": "name",
                              "type": [
                                "string",
                                "null"
                              ]
                            },
                            {
                              "name": "value",
                              "type": [
                                "string",
                                "null"
                              ]
                            }
                          ]
                        },
                        "null"
                      ]
                    },
                    "null"
                  ]
                },
                {
                  "name": "name",
                  "type": [
                    "string",
                    "null"
                  ]
                },
                {
                  "name": "size",
                  "type": [
                    "long",
                    "null"
                  ]
                },
                {
                  "name": "type",
                  "type": [
                    "string",
                    "null"
                  ]
                }
              ]
            },
            "null"
          ]
        },
        "null"
      ]
    },
    {
      "name": "history",
      "type": [
        {
          "type": "array",
          "items": [
            {
              "type": "record",
              "name": "history",
              "namespace": "bronze.rapid7",
              "fields": [
                {
                  "name": "date",
                  "type": [
                    "string",
                    "null"
                  ]
                },
                {
                  "name": "scanId",
                  "type": [
                    "long",
                    "null"
                  ]
                },
                {
                  "name": "type",
                  "type": [
                    "string",
                    "null"
                  ]
                },
                {
                  "name": "version",
                  "type": [
                    "long",
                    "null"
                  ]
                }
              ]
            },
            "null"
          ]
        },
        "null"
      ]
    },
    {
      "name": "hostName",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "hostNames",
      "type": [
        {
          "type": "array",
          "items": [
            {
              "type": "record",
              "name": "hostNames",
              "namespace": "bronze.rapid7",
              "fields": [
                {
                  "name": "name",
                  "type": [
                    "string",
                    "null"
                  ]
                },
                {
                  "name": "source",
                  "type": [
                    "string",
                    "null"
                  ]
                }
              ]
            },
            "null"
          ]
        },
        "null"
      ]
    },
    {
      "name": "id",
      "type": [
        "long",
        "null"
      ]
    },
    {
      "name": "ids",
      "type": [
        {
          "type": "array",
          "items": [
            {
              "type": "record",
              "name": "ids",
              "namespace": "bronze.rapid7",
              "fields": [
                {
                  "name": "id",
                  "type": [
                    "string",
                    "null"
                  ]
                },
                {
                  "name": "source",
                  "type": [
                    "string",
                    "null"
                  ]
                }
              ]
            },
            "null"
          ]
        },
        "null"
      ]
    },
    {
      "name": "ip",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "links",
      "type": [
        {
          "type": "array",
          "items": [
            {
              "type": "record",
              "name": "links",
              "namespace": "bronze.rapid7",
              "fields": [
                {
                  "name": "href",
                  "type": [
                    "string",
                    "null"
                  ]
                },
                {
                  "name": "rel",
                  "type": [
                    "string",
                    "null"
                  ]
                }
              ]
            },
            "null"
          ]
        },
        "null"
      ]
    },
    {
      "name": "mac",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "os",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "osCertainty",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "osFingerprint",
      "type": [
        {
          "type": "record",
          "name": "osFingerprint",
          "namespace": "bronze.rapid7",
          "fields": [
            {
              "name": "architecture",
              "type": [
                "string",
                "null"
              ]
            },
            {
              "name": "cpe",
              "type": [
                {
                  "type": "record",
                  "name": "cpe",
                  "namespace": "bronze.rapid7.osFingerprint",
                  "fields": [
                    {
                      "name": "edition",
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    {
                      "name": "part",
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    {
                      "name": "product",
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    {
                      "name": "swEdition",
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    {
                      "name": "targetHW",
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    {
                      "name": "targetSW",
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    {
                      "name": "update",
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    {
                      "name": "v2_2",
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    {
                      "name": "v2_3",
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    {
                      "name": "vendor",
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    {
                      "name": "version",
                      "type": [
                        "string",
                        "null"
                      ]
                    }
                  ]
                },
                "null"
              ]
            },
            {
              "name": "description",
              "type": [
                "string",
                "null"
              ]
            },
            {
              "name": "family",
              "type": [
                "string",
                "null"
              ]
            },
            {
              "name": "id",
              "type": [
                "long",
                "null"
              ]
            },
            {
              "name": "product",
              "type": [
                "string",
                "null"
              ]
            },
            {
              "name": "systemName",
              "type": [
                "string",
                "null"
              ]
            },
            {
              "name": "type",
              "type": [
                "string",
                "null"
              ]
            },
            {
              "name": "vendor",
              "type": [
                "string",
                "null"
              ]
            },
            {
              "name": "version",
              "type": [
                "string",
                "null"
              ]
            }
          ]
        },
        "null"
      ]
    },
    {
      "name": "rawRiskScore",
      "type": [
        "double",
        "null"
      ]
    },
    {
      "name": "riskScore",
      "type": [
        "double",
        "null"
      ]
    },
    {
      "name": "services",
      "type": [
        {
          "type": "array",
          "items": [
            {
              "type": "record",
              "name": "services",
              "namespace": "bronze.rapid7",
              "fields": [
                {
                  "name": "configurations",
                  "type": [
                    {
                      "type": "array",
                      "items": [
                        {
                          "type": "record",
                          "name": "configurations",
                          "namespace": "bronze.rapid7.services",
                          "fields": [
                            {
                              "name": "name",
                              "type": [
                                "string",
                                "null"
                              ]
                            },
                            {
                              "name": "value",
                              "type": [
                                "string",
                                "null"
                              ]
                            }
                          ]
                        },
                        "null"
                      ]
                    },
                    "null"
                  ]
                },
                {
                  "name": "databases",
                  "type": [
                    {
                      "type": "array",
                      "items": [
                        {
                          "type": "record",
                          "name": "databases",
                          "namespace": "bronze.rapid7.services",
                          "fields": [
                            {
                              "name": "id",
                              "type": [
                                "long",
                                "null"
                              ]
                            },
                            {
                              "name": "name",
                              "type": [
                                "string",
                                "null"
                              ]
                            }
                          ]
                        },
                        "null"
                      ]
                    },
                    "null"
                  ]
                },
                {
                  "name": "family",
                  "type": [
                    "string",
                    "null"
                  ]
                },
                {
                  "name": "links",
                  "type": [
                    {
                      "type": "array",
                      "items": [
                        {
                          "type": "record",
                          "name": "links",
                          "namespace": "bronze.rapid7.services",
                          "fields": [
                            {
                              "name": "href",
                              "type": [
                                "string",
                                "null"
                              ]
                            },
                            {
                              "name": "rel",
                              "type": [
                                "string",
                                "null"
                              ]
                            }
                          ]
                        },
                        "null"
                      ]
                    },
                    "null"
                  ]
                },
                {
                  "name": "name",
                  "type": [
                    "string",
                    "null"
                  ]
                },
                {
                  "name": "port",
                  "type": [
                    "long",
                    "null"
                  ]
                },
                {
                  "name": "product",
                  "type": [
                    "string",
                    "null"
                  ]
                },
                {
                  "name": "protocol",
                  "type": [
                    "string",
                    "null"
                  ]
                },
                {
                  "name": "vendor",
                  "type": [
                    "string",
                    "null"
                  ]
                },
                {
                  "name": "version",
                  "type": [
                    "string",
                    "null"
                  ]
                }
              ]
            },
            "null"
          ]
        },
        "null"
      ]
    },
    {
      "name": "software",
      "type": [
        {
          "type": "array",
          "items": [
            {
              "type": "record",
              "name": "software",
              "namespace": "bronze.rapid7",
              "fields": [
                {
                  "name": "configurations",
                  "type": [
                    {
                      "type": "array",
                      "items": [
                        {
                          "type": "record",
                          "name": "configurations",
                          "namespace": "bronze.rapid7.software",
                          "fields": [
                            {
                              "name": "name",
                              "type": [
                                "string",
                                "null"
                              ]
                            },
                            {
                              "name": "value",
                              "type": [
                                "string",
                                "null"
                              ]
                            }
                          ]
                        },
                        "null"
                      ]
                    },
                    "null"
                  ]
                },
                {
                  "name": "cpe",
                  "type": [
                    {
                      "type": "record",
                      "name": "cpe",
                      "namespace": "bronze.rapid7.software",
                      "fields": [
                        {
                          "name": "part",
                          "type": [
                            "string",
                            "null"
                          ]
                        },
                        {
                          "name": "product",
                          "type": [
                            "string",
                            "null"
                          ]
                        },
                        {
                          "name": "update",
                          "type": [
                            "string",
                            "null"
                          ]
                        },
                        {
                          "name": "v2_2",
                          "type": [
                            "string",
                            "null"
                          ]
                        },
                        {
                          "name": "v2_3",
                          "type": [
                            "string",
                            "null"
                          ]
                        },
                        {
                          "name": "vendor",
                          "type": [
                            "string",
                            "null"
                          ]
                        },
                        {
                          "name": "version",
                          "type": [
                            "string",
                            "null"
                          ]
                        }
                      ]
                    },
                    "null"
                  ]
                },
                {
                  "name": "description",
                  "type": [
                    "string",
                    "null"
                  ]
                },
                {
                  "name": "family",
                  "type": [
                    "string",
                    "null"
                  ]
                },
                {
                  "name": "id",
                  "type": [
                    "long",
                    "null"
                  ]
                },
                {
                  "name": "product",
                  "type": [
                    "string",
                    "null"
                  ]
                },
                {
                  "name": "type",
                  "type": [
                    "string",
                    "null"
                  ]
                },
                {
                  "name": "vendor",
                  "type": [
                    "string",
                    "null"
                  ]
                },
                {
                  "name": "version",
                  "type": [
                    "string",
                    "null"
                  ]
                }
              ]
            },
            "null"
          ]
        },
        "null"
      ]
    },
    {
      "name": "type",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "userGroups",
      "type": [
        {
          "type": "array",
          "items": [
            {
              "type": "record",
              "name": "userGroups",
              "namespace": "bronze.rapid7",
              "fields": [
                {
                  "name": "id",
                  "type": [
                    "long",
                    "null"
                  ]
                },
                {
                  "name": "name",
                  "type": [
                    "string",
                    "null"
                  ]
                }
              ]
            },
            "null"
          ]
        },
        "null"
      ]
    },
    {
      "name": "users",
      "type": [
        {
          "type": "array",
          "items": [
            {
              "type": "record",
              "name": "users",
              "namespace": "bronze.rapid7",
              "fields": [
                {
                  "name": "fullName",
                  "type": [
                    "string",
                    "null"
                  ]
                },
                {
                  "name": "id",
                  "type": [
                    "long",
                    "null"
                  ]
                },
                {
                  "name": "name",
                  "type": [
                    "string",
                    "null"
                  ]
                }
              ]
            },
            "null"
          ]
        },
        "null"
      ]
    },
    {
      "name": "vulnerabilities",
      "type": [
        {
          "type": "record",
          "name": "vulnerabilities",
          "namespace": "bronze.rapid7",
          "fields": [
            {
              "name": "critical",
              "type": [
                "long",
                "null"
              ]
            },
            {
              "name": "exploits",
              "type": [
                "long",
                "null"
              ]
            },
            {
              "name": "malwareKits",
              "type": [
                "long",
                "null"
              ]
            },
            {
              "name": "moderate",
              "type": [
                "long",
                "null"
              ]
            },
            {
              "name": "severe",
              "type": [
                "long",
                "null"
              ]
            },
            {
              "name": "total",
              "type": [
                "long",
                "null"
              ]
            }
          ]
        },
        "null"
      ]
    },
    {
      "name": "site_id",
      "type": [
        "string",
        "null"
      ],
      "default": null
    },
    {
      "name": "site_name",
      "type": [
        "string",
        "null"
      ],
      "default": null
    },
    {
      "name": "ingest_ts",
      "type": [
        "long",
        "null"
      ],
      "default": null
    }
  ]
}
