{
  "type": "record",
  "name": "sentinal",
  "namespace": "bronze",
  "fields": [
    {
      "name": "accountId",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "accountName",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "activeDirectory",
      "type": [
        {
          "type": "record",
          "name": "activeDirectory",
          "namespace": "bronze.sentinal",
          "fields": [
            {
              "name": "computerDistinguishedName",
              "type": [
                "string",
                "null"
              ]
            },
            {
              "name": "computerMemberOf",
              "type": [
                {
                  "type": "array",
                  "items": [
                    "string",
                    "null"
                  ]
                },
                "null"
              ]
            },
            {
              "name": "lastUserDistinguishedName",
              "type": [
                "string",
                "null"
              ]
            },
            {
              "name": "lastUserMemberOf",
              "type": [
                {
                  "type": "array",
                  "items": [
                    "string",
                    "null"
                  ]
                },
                "null"
              ]
            },
            {
              "name": "userPrincipalName",
              "type": [
                "string",
                "null"
              ]
            }
          ]
        },
        "null"
      ]
    },
    {
      "name": "activeProtection",
      "type": [
        {
          "type": "array",
          "items": [
            "string",
            "null"
          ]
        },
        "null"
      ]
    },
    {
      "name": "activeThreats",
      "type": [
        "long",
        "null"
      ]
    },
    {
      "name": "agentVersion",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "allowRemoteShell",
      "type": [
        "boolean",
        "null"
      ]
    },
    {
      "name": "appsVulnerabilityStatus",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "computerName",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "consoleMigrationStatus",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "containerizedWorkloadCounts",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "coreCount",
      "type": [
        "long",
        "null"
      ]
    },
    {
      "name": "cpuCount",
      "type": [
        "long",
        "null"
      ]
    },
    {
      "name": "cpuId",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "createdAt",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "detectionState",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "domain",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "encryptedApplications",
      "type": [
        "boolean",
        "null"
      ]
    },
    {
      "name": "externalId",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "externalIp",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "firewallEnabled",
      "type": [
        "boolean",
        "null"
      ]
    },
    {
      "name": "firstFullModeTime",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "fullDiskScanLastUpdatedAt",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "groupId",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "groupIp",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "groupName",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "hasContainerizedWorkload",
      "type": [
        "boolean",
        "null"
      ]
    },
    {
      "name": "id",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "inRemoteShellSession",
      "type": [
        "boolean",
        "null"
      ]
    },
    {
      "name": "infected",
      "type": [
        "boolean",
        "null"
      ]
    },
    {
      "name": "installerType",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "isActive",
      "type": [
        "boolean",
        "null"
      ]
    },
    {
      "name": "isAdConnector",
      "type": [
        "boolean",
        "null"
      ]
    },
    {
      "name": "isDecommissioned",
      "type": [
        "boolean",
        "null"
      ]
    },
    {
      "name": "isHyperAutomate",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "isPendingUninstall",
      "type": [
        "boolean",
        "null"
      ]
    },
    {
      "name": "isUninstalled",
      "type": [
        "boolean",
        "null"
      ]
    },
    {
      "name": "isUpToDate",
      "type": [
        "boolean",
        "null"
      ]
    },
    {
      "name": "lastActiveDate",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "lastIpToMgmt",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "lastLoggedInUserName",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "lastSuccessfulScanDate",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "licenseKey",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "locationEnabled",
      "type": [
        "boolean",
        "null"
      ]
    },
    {
      "name": "locationType",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "locations",
      "type": [
        {
          "type": "array",
          "items": [
            {
              "type": "record",
              "name": "locations",
              "namespace": "bronze.sentinal",
              "fields": [
                {
                  "name": "id",
                  "type": [
                    "string",
                    "null"
                  ]
                },
                {
                  "name": "name",
                  "type": [
                    "string",
                    "null"
                  ]
                },
                {
                  "name": "scope",
                  "type": [
                    "string",
                    "null"
                  ]
                }
              ]
            },
            "null"
          ]
        },
        "null"
      ]
    },
    {
      "name": "machineSid",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "machineType",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "missingPermissions",
      "type": [
        {
          "type": "array",
          "items": [
            "string",
            "null"
          ]
        },
        "null"
      ]
    },
    {
      "name": "mitigationMode",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "mitigationModeSuspicious",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "modelName",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "networkInterfaces",
      "type": [
        {
          "type": "array",
          "items": [
            {
              "type": "record",
              "name": "networkInterfaces",
              "namespace": "bronze.sentinal",
              "fields": [
                {
                  "name": "gatewayIp",
                  "type": [
                    "string",
                    "null"
                  ]
                },
                {
                  "name": "gatewayMacAddress",
                  "type": [
                    "string",
                    "null"
                  ]
                },
                {
                  "name": "id",
                  "type": [
                    "string",
                    "null"
                  ]
                },
                {
                  "name": "inet",
                  "type": [
                    {
                      "type": "array",
                      "items": [
                        "string",
                        "null"
                      ]
                    },
                    "null"
                  ]
                },
                {
                  "name": "inet6",
                  "type": [
                    {
                      "type": "array",
                      "items": [
                        "string",
                        "null"
                      ]
                    },
                    "null"
                  ]
                },
                {
                  "name": "name",
                  "type": [
                    "string",
                    "null"
                  ]
                },
                {
                  "name": "physical",
                  "type": [
                    "string",
                    "null"
                  ]
                }
              ]
            },
            "null"
          ]
        },
        "null"
      ]
    },
    {
      "name": "networkQuarantineEnabled",
      "type": [
        "boolean",
        "null"
      ]
    },
    {
      "name": "networkStatus",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "operationalState",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "operationalStateExpiration",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "osArch",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "osName",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "osRevision",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "osStartTime",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "osType",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "osUsername",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "proxyStates",
      "type": [
        {
          "type": "record",
          "name": "proxyStates",
          "namespace": "bronze.sentinal",
          "fields": [
            {
              "name": "console",
              "type": [
                "boolean",
                "null"
              ]
            },
            {
              "name": "deepVisibility",
              "type": [
                "string",
                "null"
              ]
            }
          ]
        },
        "null"
      ]
    },
    {
      "name": "rangerStatus",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "rangerVersion",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "registeredAt",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "remoteProfilingState",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "remoteProfilingStateExpiration",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "scanAbortedAt",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "scanFinishedAt",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "scanStartedAt",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "scanStatus",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "serialNumber",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "showAlertIcon",
      "type": [
        "boolean",
        "null"
      ]
    },
    {
      "name": "siteId",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "siteName",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "storageName",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "storageType",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "tags",
      "type": [
        {
          "type": "record",
          "name": "tags",
          "namespace": "bronze.sentinal",
          "fields": [
            {
              "name": "sentinelone",
              "type": [
                {
                  "type": "array",
                  "items": [
                    "string",
                    "null"
                  ]
                },
                "null"
              ]
            }
          ]
        },
        "null"
      ]
    },
    {
      "name": "threatRebootRequired",
      "type": [
        "boolean",
        "null"
      ]
    },
    {
      "name": "totalMemory",
      "type": [
        "long",
        "null"
      ]
    },
    {
      "name": "updatedAt",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "userActionsNeeded",
      "type": [
        {
          "type": "array",
          "items": [
            "string",
            "null"
          ]
        },
        "null"
      ]
    },
    {
      "name": "uuid",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "ingest_ts",
      "type": [
        "long",
        "null"
      ],
      "default": null
    }
  ]
}
