{
  "type": "record",
  "name": "fortisiem_monitor_raw_avro",
  "namespace": "bronze.fortisiem",
  "fields": [
    {
      "name": "source_platform",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "customer_tenant_organization",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "source_object_type",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "source_object_id",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "extraction_timestamp",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "source_event_update_timestamp",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "api_endpoint_export_query_identity",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "cursor_window",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "payload_hash_fingerprint",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "ingestion_run_batch_identity",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "object_id",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "ingest_ts",
      "type": [
        "null",
        "long"
      ],
      "default": null
    },
    {
      "name": "Monitor_Type_Category",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "Perf_Object_Frequency",
      "type": [
        "null",
        "long"
      ],
      "default": null
    },
    {
      "name": "Customer_ID",
      "type": [
        "null",
        "long"
      ],
      "default": null
    },
    {
      "name": "Perf_Object_Threshold",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "Monitor_Status",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "Device_Type_Vendor",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "Discover_Status",
      "type": [
        "null",
        "long"
      ],
      "default": null
    },
    {
      "name": "Device_IP",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "Monitor_Target",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "Monitor_Status_Description",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "Device_Type_Model",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "Perf_Object_Method",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "Perf_Object_Description",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "Latest_Monitor_time",
      "type": [
        "null",
        "long"
      ],
      "default": null
    },
    {
      "name": "Monitor_Enabled_Flag",
      "type": [
        "null",
        "boolean"
      ],
      "default": null
    },
    {
      "name": "Monitor_Frequency",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "Customer_Name",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "Device_Name",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "Monitor_Type_Display_Name",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "Perf_Object_System_Defined_Flag",
      "type": [
        "null",
        "boolean"
      ],
      "default": null
    }
  ]
}